---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mattsday/le-pcf-on-gcp-base
    tag: "latest"

inputs:
- name: git-assets

outputs:
- name: app-info

run:
	path: git-assets/pipeline/scripts/update-cert.sh

